server:
  port: 8081
spring:
  application:
    name: item-service
  datasource:
    url: jdbc:mysql://localhost:3306/heima
    username: root
    password: 12345678
    hikari:
      maximum-pool-size: 30
      minimum-idle: 10
